version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cocobu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: cocobu
      MYSQL_USER: cocobu
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-devpassword123}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
