[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run db:generate",
  "npm run build --workspace=@cocobu/database",
  "npm run build --workspace=@cocobu/api"
]

[start]
cmd = "npm run db:migrate:deploy && npm run start --workspace=@cocobu/api"
