[build]
builder = "NIXPACKS"
buildCommand = "npm run build:api"

[deploy]
startCommand = "npm run db:migrate:deploy && npm run start --workspace=@cocobu/api"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
