[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && npm install && npm run db:generate && npm run build --workspace=@cocobu/api"

[deploy]
startCommand = "cd ../.. && npm run db:migrate:deploy && cd apps/api && node dist/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
